final Map<String, String> en = {
//registration screen

  "Helps you to consult patient Virtually":
      "Helps you to consult patient Virtually",
  "Engage with patient through video and audio":
      "Engage with patient through video and audio",
  "Keep on track your patient Health": "Keeps on track your patient Health",
  "Username": "Username",
  "password": "Password",
  "CONTINUE": "CONTINUE",
  "By continuing, You agree that you have read and accept our T&C and Privacy Policy":
      "By continuing, You agree that you have read and accept our T&C and Privacy Policy",
  "LoggedIn Successfully": "LoggedIn Successfully",
  "Invalid Credential": "Invalid Credential",

//Home Screen
  "Home": "Home",
  "AlloLab": "AlloLab",
  "Welcome": "Welcome",
  "Worker ID": "Worker ID",
  "Recently Added Patient": "Recently Added Patient",
  "Mobile No:": "Mobile No:",
  "Start Screening": "Start Screening",
  "Select Language": "Select Language",
  "English": "English",
  "Tamil": "Tamil",
  "Hindi": "Hindi",
  "Face Recognition": "Face Recognition",
  "Start Screening with Face Recognition":
      "Start Screening with Face Recognition",
  "CAPTURE": "CAPTURE",
  "User Not Found": "User Not Found",
  "Search with Phone Number": "Search with Phone Number",
  "Enter Phone Number": "Enter Phone Number",
  "Add New Patient": "Add New Patient",
  "Add Patient to Start Screening": "Add Patient to Start Screening",
  "Personal Details": "Personal Details",
  "Capture Image": "Capture Image",
  "Name": "Name",
  "EmailID": "EmailID",
  "Phone Number": "Phone Number",
  "Completed and Upcoming": "Completed and Upcoming",
  "Gender": "Gender",
  "Male": "Male",
  "Female": "Female",
  "Blood Group": "Blood Group",
  "Date of Birth": "Date of Birth",
  "Age": "Age",
  "OK": "OK",
  "CANCEL": "CANCEL",
  "Address Details": "Address Details",
  "AddressLine": "AddressLine",
  "Pincode": "Pincode",
  "City": "City",
  "State": "State",
  "Enter Correct Pincode": "Enter Correct Pincode",
  "Patient Name": "Patient Name",
  "Checkup Details": "Checkup Details",
  "Appointment": "Appointment",
  "Book an Appointment": "Book on Appointment",
  "Select Doctor": "Select Doctor",
  "Appointment Date": "Appointment Date",
  "View Available Slots": "View Available Slots",
  "No Slot Selected": "No Slot Selected",
  "Diagnosis Desc": "Diagnosis Desc",
  "Book": "Book",
  "Appointment Book Successfully": "Appointment Book Successfully",
  "CheckUp": "CheckUp",
  "No CheckUp found": "No CheckUp found",
  "Today": "Today",
  "No available slot for selected date": "No available slot for selected date",
  "View Appointment": "View Appointment",
  "Completed": "Completed",
  "Appointments": "Appointments",
  "Upcoming": "Upcoming",
  "Date": "Date",
  "Date: ": "Date: ",
  "Time": "Time",
  "CANCELED": "CANCELED",
  "Checkup Time": "Checkup Time",
  "Status": "Status",
  "View Appointment": "View Appointment",
  "Cancel Appointment": "Cancel Appointment",
  "Add Symptoms and Vitals": "Add Symptoms and Vitals",
  "Select Symptoms": "Select Symptoms",
  "Body Pain": "Body pain",
  "Burning Stomach": "Burning Stomach",
  "Cold Cough": "Cold Cough",
  "Dizziness": "Dizziness",
  "Headache": "Headache",
  "Vomiting": "Vomiting",
  "Other": "Other",
  "NEXT": "NEXT",
  "Vitals": "Vitals",
  "Blood Pressure": "Blood Pressure",
  "Temperature": "Temperature",
  "Blood Saturation": "Blood Saturation",
  "Heart Rate": "Heart Rate",
  "Blood Glucose": "Blood Glucose",
  "BMI": "BMI",
  "Respiratory Rate": "Respiratory Rate",
  "HRV": "HRV",
  "BACK": "BACK",
  "SAVE": "SAVE",
  "CheckUp Added Successfully": "CheckUp Added Successfully",
  "CheckUp completed": "CheckUp completed",
  "COMPLETED": "COMPLETED",
  "Appointment Status": "Appointment Status",
  "Doctor Name": "Doctor Name",
  "Health Status": "Health Status",
  "NORMAL": "NORMAL",
  "Case Summary": "Case Summary",
  "Prescription": "Prescription",
  "Tablets": "Tablets",
  "Units": "Units",
  "Timing": "Timing",
  "Requested lab supported": "Requested lab supported",
  "Next Appointment Date": "Next Appointment Date",
  "Next Appointment Time": "Next Appointment Time",
  "Symptoms": "Symptoms",
  "Are you sure to cancel the appointment?":
      "Are you sure to cancel the appointment?",
  "Screening": "Screening",
  "Go to Screening": "Go to Screening",
  "Reports": "Reports",
  "Report Details": "Report Details",
  "Report": "Report",
  "SCAN AND ADD NEW REPORT": "SCAN AND ADD NEW REPORT",
  "Click Add Images Button": "Click Add Images Button",
  "NO IMAGE": "NO IMAGE",
  "No Report Added": "No Report Added",
  "ADD IMAGE": "ADD IMAGE",
  "Choose Photo from :": "Choose Photo from :",
  "Type of Report": "Type of Report",
  "Write Description": "Write Description",
  "ADD REPORT": "ADD REPORT",
  "Report Added Successfully": "Report Added Successfully",
  "Report Deleted Successfully": "Report Deleted Successfully",
  "Report Date: ": "Report Date: ",
  "After Food": "After Food",
  "Before Food": "Before Food",
  "Before Walk": "Before Walk",
  "After Walk": "After Walk",
  "Report Time: ": "Report Time: ",
  "Report desc: ": "Report desc: ",
  "UPDATE IMAGE": "UPDATE IMAGE",
  "DELETE REPORT": "DELETE REPORT",
  "UPDATE REPORT": "UPDATE REPORT",
  "Report Updated Successfully": "Report Updated Successfully",
  "Education": "Education",
  "Knowledge Transfer": "Knowledge Transfer",
  "Sorry No Awareness Post Found": "sorry No Awareness Post Found",
  "Patient List": "Patient List",
  "Search Patient By Name": "Search Patient By Name",

//Chat screen

  "Chat": "Chat",
  "PATIENTS": "PATIENTS",
  "DOCTORS": "DOCTORS",
  "NURSE": "NURSE",
  "Type a message": "Type a message",
  "View Case Details": "View Case Details",

//Settings Screen

  "Settings": "Settings",
  "General Details": "General Details",
  "Year of Experience": "Year of Experience",
  "Title": "Title",
  "Address": "Address",
  "Edit Profile": "Edit Profile",
  "Notification": "Notification",
  "ON": "ON",
  "OFF": "OFF",
  "Terms & Conditions": "Terms & Conditions",
  "Privacy Policy": "Privacy Policy",
  "Help": "Help",
  "Contact Us": "Contact Us",
  "Tell us what's going on": "Tell Us what's going on",
  "Tell us why you're reaching us": "Tell us why you're reaching us",
  "Something not Working": "Something not Working",
  "Feature Request": "Feature Request",
  "Question": "Question",
  "FeedBack": "Feedback",
  "How do you feel? (Optional)": "How do you feel? (Optional)",
  "SEND": "SEND",
  "App Info": "App Info",
  "Log out": "Log out",
  "Are you sure to log out?": "Are you sure to log out?",
  "No": "No",
  "Yes": "Yes",
  "Other": "Other",
  "Language": "Language",
};
