final Map<String, String> hi = {
//registration screen

  "Helps you to consult patient Virtually":
      "वस्तुत रोगी से परामर्श करने में आपकी सहायता करता है",
  "Engage with patient through video and audio":
      "वीडियो और ऑडियो के माध्यम से रोगी से जुड़ें",
  "Keep on track your patient Health": "अपने मरीज के स्वास्थ्य पर नज़र रखता है",
  "Username": "उपयोगकर्ता नाम",
  "password": "पासवर्ड",
  "CONTINUE": "पासवर्ड",
  "By continuing, You agree that you have read and accept our T&C and Privacy Policy":
      "जारी रखकर, आप सहमत हैं कि आपने हमारी नियम एवं शर्तें और गोपनीयता नीति को पढ़ लिया है और स्वीकार कर लिया है",
  "LoggedIn Successfully": "सफलतापूर्वक लॉग इन हो चुका है",
  "Invalid Credential": "अमान्य क्रेडेंशियल",

//Home Screen
  "Home": "घर",
  "AlloLab": "एलोलैब",
  "Welcome": "स्वागत है",
  "Worker ID": "कार्यकर्ता आईडी",
  "Recently Added Patient": "हाल ही में जोड़ा गया रोगी",
  "Mobile No:": "मोबाइल नहीं है:",
  "Start Screening": "स्क्रीनिंग शुरू करें",
  "Select Language": "भाषा चुने",
  "English": "अंग्रेज़ी",
  "Tamil": "तमिल",
  "Hindi": "हिन्दी",
  "Face Recognition": "चेहरा पहचान",
  "Start Screening with Face Recognition":
      "चेहरे की पहचान के साथ स्क्रीनिंग शुरू करें",
  "CAPTURE": "कब्जा",
  "User Not Found": "उपयोगकर्ता नहीं मिला",
  "Search with Phone Number": "फ़ोन नंबर से खोजें",
  "Enter Phone Number": "फोन नंबर दर्ज",
  "Add New Patient": "नया रोगी जोड़ें",
  "Add Patient to Start Screening":
      "स्क्रीनिंग शुरू करने के लिए रोगी को जोड़ें",
  "Personal Details": "व्यक्तिगत विवरण",
  "Capture Image": "छवि कैप्चर करें",
  "Name": "नाम",
  "EmailID": "ईमेल आईडी",
  "Phone Number": "फ़ोन नंबर",
  "Gender": "लिंग",
  "Male": "पुरुष",
  "Female": "महिला",
  "Blood Group": "रक्त समूह",
  "Date of Birth": "जन्म की तारीख",
  "Age": "उम्र",
  "OK": "ठीक है",
  "CANCEL": "रद्द करना",
  "Address Details": "पते का विवरण",
  "AddressLine": "पता पंक्ति",
  "Pincode": "पिन कोड",
  "City": "शहर",
  "State": "राज्य",
  "Enter Correct Pincode": "सही पिनकोड दर्ज करें",
  "Patient Name": "रोगी का नाम",
  "Checkup Details": "चेकअप विवरण",
  "Appointment": "मुलाकात",
  "Book an Appointment": "एक अपॉइंटमेंट बुक करें",
  "Select Doctor": "डॉक्टर का चयन करें",
  "Appointment Date": "मिलने की तारीख",
  "View Available Slots": "उपलब्ध स्लॉट देखें",
  "No Slot Selected": "कोई स्लॉट नहीं चुना गया",
  "Diagnosis Desc": "निदान विवरण",
  "Book": "पुस्तक",
  "Appointment Book Successfully": "नियुक्ति पुस्तक सफलतापूर्वक",
  "CheckUp": "जांच",
  "No CheckUp found": "कोई चेकअप नहीं मिला",
  "Today": "आज",
  "No available slot for selected date":
      "चयनित तिथि के लिए कोई स्लॉट उपलब्ध नहीं है",
  "View Appointment": "अपॉइंटमेंट देखें",
  "Completed": "पूरा किया हुआ",
  "Appointments": "नियुक्तियाँ",
  "CANCELED": "रद्द",
  "Upcoming": "आगामी",
  "Date": "दिनांक",
  "Date: ": "दिनांक: ",
  "Time": "समय",
  "Status": "स्थिति",
  "Checkup Time": "चेकअप समय",
  "View Appointment": "अपॉइंटमेंट देखें",
  "Cancel Appointment": "अपॉइंटमेंट रद्द करें",
  "Add Symptoms and Vitals": "लक्षण और महत्वपूर्ण जोड़ें",
  "Select Symptoms": "लक्षण चुनें",
  "Body Pain": "बदन दर्द",
  "Burning Stomach": "जलता हुआ पेट",
  "Cold Cough": "ठंड खांसी",
  "Dizziness": "चक्कर आना",
  "Headache": "सिरदर्द",
  "Vomiting": "उल्टी करना",
  "Other": "अन्य",
  "NEXT": "अगला",
  "Vitals": "महत्वपूर्ण",
  "Blood Pressure": "रक्तचाप",
  "After Food": "भोजन के बाद",
  "Temperature": "तापमान",
  "Before Food": "भोजन से पहले",
  "Blood Saturation": "रक्त संतृप्ति",
  "Before Walk": "चलने से पहले",
  "After Walk": "चलने के बाद",
  "Heart Rate": "हृदय दर",
  "Blood Glucose": "रक्त द्राक्ष - शर्करा",
  "BMI": "बीएमआई",
  "Respiratory Rate": "श्वसन दर",
  "HRV": "एचआरवी",
  "BACK": "पीछे",
  "SAVE": "सहेजें",
  "CheckUp Added Successfully": "चेकअप सफलतापूर्वक जोड़ा गया",
  "CheckUp completed": "चेकअप पूरा हुआ",
  "COMPLETED": "पूरा किया हुआ",
  "Appointment Status": "नियुक्ति की स्थिति",
  "Doctor Name": "डॉक्टर का नाम",
  "Health Status": "स्वास्थ्य की स्थिति",
  "NORMAL": "सामान्य",
  "Completed and Upcoming": "पूर्ण और आगामी",
  "Case Summary": "केस सारांश",
  "Prescription": "पर्चे",
  "Tablets": "गोलियाँ",
  "Units": "इकाइयों",
  "Timing": "समय",
  "Requested lab supported": "अनुरोधित लैब समर्थित",
  "Next Appointment Date": "अगली नियुक्ति तिथि",
  "Next Appointment Time": "अगली नियुक्ति समय",
  "Symptoms": "लक्षण",
  "Are you sure to cancel the appointment?":
      "क्या आप निश्चित रूप से अपॉइंटमेंट रद्द करना चाहते हैं?",
  "Screening": "स्क्रीनिंग",
  "Go to Screening": "स्क्रीनिंग पर जाएं",
  "Reports": "रिपोर्ट",
  "Report Details": "रिपोर्ट विवरण",
  "Report": "प्रतिवेदन",
  "SCAN AND ADD NEW REPORT": "स्कैन करें और नई रिपोर्ट जोड़ें",
  "Click Add Images Button": "छवियां जोड़ें बटन पर क्लिक करें",
  "NO IMAGE": "कोई तस्वीर नहीं",
  "No Report Added": "कोई रिपोर्ट नहीं जोड़ी गई",
  "ADD IMAGE": "छवि जोड़ें",
  "Choose Photo from :": "से फोटो चुनें:",
  "Type of Report": "रिपोर्ट का प्रकार",
  "Write Description": "विवरण लिखें",
  "ADD REPORT": "रिपोर्ट जोड़ें",
  "Report Added Successfully": "रिपोर्ट सफलतापूर्वक जोड़ी गई",
  "Report Deleted Successfully": "रिपोर्ट सफलतापूर्वक हटाई गई",
  "Report Date: ": "रिपोर्ट तिथि: ",
  "Report Time: ": "रिपोर्ट समय: ",
  "Report desc: ": "रिपोर्ट विवरण: ",
  "UPDATE IMAGE": "अद्यतन छवि",
  "DELETE REPORT": "रिपोर्ट हटाएं",
  "UPDATE REPORT": "अपडेट रिपोर्ट",
  "Report Updated Successfully": "रिपोर्ट सफलतापूर्वक अपडेट की गई",
  "Education": "शिक्षा",
  "Knowledge Transfer": "ज्ञान स्थानांतरण",
  "Sorry No Awareness Post Found": "क्षमा करें कोई जागरूकता पोस्ट नहीं मिला",
  "Patient List": "रोगी सूची",
  "Search Patient By Name": "नाम से रोगी खोजें",

//Chat screen

  "Chat": "चैट",
  "PATIENTS": "रोगी",
  "DOCTORS": "डॉक्टर",
  "NURSE": "नर्स",
  "Type a message": "एक संदेश लिखें",
  "View Case Details": "केस विवरण देखें",

//Settings Screen

  "Settings": "समायोजन",
  "General Details": "सामान्य विवरण",
  "Year of Experience": "अनुभव का वर्ष",
  "Title": "शीर्षक",
  "Address": "पता",
  "Edit Profile": "प्रोफ़ाइल संपादित करें",
  "Notification": "अधिसूचना",
  "ON": "पर",
  "OFF": "बंद",
  "Terms & Conditions": "नियम एवं शर्तें",
  "Privacy Policy": "गोपनीयता नीति",
  "Help": "मदद",
  "Contact Us": "संपर्क करें",
  "Tell us what's going on": "हमें बताओ क्या हो रहा है",
  "Tell us why you're reaching us":
      "हमें बताएं कि आप हम तक क्यों पहुंच रहे हैं",
  "Something not Working": "कुछ काम नहीं कर रहा",
  "Feature Request": "महत्वपूर्ण लेख मांगना",
  "Question": "प्रश्न",
  "FeedBack": "प्रतिक्रिया",
  "How do you feel? (Optional)": "आप कैसा महसूस कर रहे हैं? (वैकल्पिक)",
  "SEND": "भेजना",
  "App Info": "अनुप्रयोग की जानकारी",
  "Log out": "लॉग आउट",
  "Are you sure to log out?": "क्या आप निश्चित रूप से लॉग आउट करना चाहते हैं?",
  "No": "नहीं",
  "Yes": "हां",
  "Other": "अन्य",
  "Language": "भाषा",
};
