final Map<String, String> ta = {
//registration screen

  "Helps you to consult patient Virtually":
      "உண்மையில் நோயாளியைக் கலந்தாலோசிக்க உங்களுக்கு உதவுகிறது",
  "Engage with patient through video and audio":
      "வீடியோ மற்றும் ஆடியோ மூலம் நோயாளியுடன் ஈடுபடுங்கள்",
  "Keep on track your patient Health":
      "உங்கள் நோயாளியின் ஆரோக்கியத்தை கண்காணிக்கும்",
  "Username": "பயனர் பெயர்",
  "password": "கடவுச்சொல்",
  "CONTINUE": "தொடரவும்",
  "By continuing, You agree that you have read and accept our T&C and Privacy Policy":
      "தொடர்வதன் மூலம், எங்கள் T&C மற்றும் தனியுரிமைக் கொள்கையைப் படித்து ஏற்றுக்கொண்டீர்கள் என்பதை ஒப்புக்கொள்கிறீர்கள்",
  "LoggedIn Successfully": "புகுபதிகை வெற்றிகரமாக",
  "Invalid Credential": "தவறான நற்சான்றிதழ்",

//Home Screen
  "Home": "முகப்பு",
  "AlloLab": "அலோலேப்",
  "Welcome": "வணக்கம்",
  "Worker ID": "தொழிலாளி ஐடி",
  "Recently Added Patient": "சமீபத்தில் சேர்க்கப்பட்ட நோயாளி",
  "Mobile No:": "அலைபேசி எண்:",
  "Start Screening": "திரையிடல் தொடங்கு",
  "Select Language": "மொழியை தேர்ந்தெடுங்கள்",
  "English": "ஆங்கிலம்",
  "Tamil": "தமிழ்",
  "Hindi": "இந்தி",
  "Face Recognition": "முகத்தை அடையாளம் காணுதல்",
  "Start Screening with Face Recongnition":
      "முகம் அங்கீகாரத்துடன் திரையிடலைத் தொடங்கு",
  "CAPTURE": "பிடிப்பு",
  "User Not Found": "பயனர் கிடைக்கவில்லை",
  "Search with Phone Number": "தொலைபேசி எண்ணைக் கொண்டு தேடு",
  "Enter Phone Number": "தொலைபேசி எண்ணை உள்ளிடவும்",
  "Add New Patient": "புதிய நோயாளியைச் சேர்",
  "Add Patient to Start Screening": "திரையிடல் தொடங்க நோயாளியைச் சேர்க்கவும்",
  "Personal Details": "தனிப்பட்ட விவரங்கள்",
  "Capture Image": "படத்தை பிடி",
  "Name": "பெயர்",
  "EmailID": "மின்னஞ்சல் முகவரி",
  "Phone Number": "தொலைபேசி எண்",
  "Gender": "பாலினம்",
  "Male": "ஆண்",
  "Female": "பெண்",
  "Blood Group": "இரத்த வகை",
  "Date of Birth": "பிறந்த தேதி",
  "Age": "வயது",
  "OK": "சரி",
  "CANCEL": "ரத்துசெய்",
  "Address Details": "முகவரி விவரங்கள்",
  "AddressLine": "முகவரி",
  "Pincode": "அஞ்சல் குறியீடு",
  "City": "நகரம்",
  "State": "நிலை",
  "Enter Correct Pincode": "சரியான பின்கோடை உள்ளிடவும்",
  "Patient Name": "நோயாளியின் பெயர்",
  "Checkup Details": "சரிபார்ப்பு விவரங்கள்",
  "Appointment": "அப்பாயிண்ட்மெண்ட்",
  "Book an Appointment": "ஒரு சந்திப்பை முன்பதிவு செய்யுங்கள்",
  "Select Doctor": "டாக்டரை தேர்ந்தெடு",
  "Appointment Date": "அப்பயிண்ட்மெண்ட் தேதி",
  "View Available Slots": "கிடைக்கும் இடங்களைக் காண்க",
  "No Slot Selected": "ஸ்லாட் எதுவும் தேர்ந்தெடுக்கப்படவில்லை",
  "Diagnosis Desc": "நோயறிதல் விவரம்",
  "Book": "பதிவு",
  "Appointment Book Successfully": "அப்பாயிண்ட்மெண்ட் புத்தகம் வெற்றிகரமாக",
  "CheckUp": "சோதனை",
  "No CheckUp found": "சோதனை இல்லை",
  "Today": "இன்று",
  "No available slot for selected date":
      "தேர்ந்தெடுக்கப்பட்ட தேதிக்கு ஸ்லாட் இல்லை",
  "View appointment": "அப்பாயிண்ட்மெண்ட் பார்க்கவும்",
  "Completed": "நிறைவு",
  "Appointments": "நியமனங்கள்",
  "Upcoming": "வரவிருக்கும்",
  "Date": "தேதி",
  "Date: ": "தேதி: ",
  "Time": "நேரம்",
  "Status": "நிலை",
  "View Appointment": "அப்பாயிண்ட்மெண்ட் பார்க்கவும்",
  "Cancel Appointment": "அப்பயிண்ட்மெண்ட்டை ரத்து செய்",
  "Add Symptoms and Vitals": "அறிகுறிகள் மற்றும் உயிர்களைச் சேர்",
  "Select Symptoms": "அறிகுறிகளைத் தேர்ந்தெடு",
  "Body Pain": "உடல் வலி",
  "Burning Stomach": "எரியும் வயிறு",
  "Cold Cough": "சளி இருமல்",
  "Dizziness": "தலைச்சுற்றல்",
  "Headache": "தலைவலி",
  "Vomiting": "வாந்தி",
  "Other": "மற்றவை",
  "NEXT": "அடுத்தது",
  "Vitals": "உயிரினங்கள்",
  "Blood Pressure": "இரத்த அழுத்தம்",
  "Temperature": "வெப்ப நிலை",
  "Blood Saturation": "இரத்த செறிவு",
  "Heart Rate": "இதய துடிப்பு",
  "Blood Glucose": "இரத்த குளுக்கோஸ்",
  "BMI": "பிஎம்ஐ",
  "Respiratory Rate": "சுவாச விகிதம்",
  "HRV": "எச்ஆர்வி",
  "BACK": "மீண்டும்",
  "Completed and Upcoming": "நிறைவு மற்றும் வரவிருக்கும்",
  "SAVE": "சேமி",
  "CheckUp Added Successfully": "சரிபார்ப்பு வெற்றிகரமாக சேர்க்கப்பட்டது",
  "CheckUp completed": "சோதனை முடிந்தது",
  "COMPLETED": "நிறைவு",
  "Appointment Status": "நியமன நிலை",
  "Doctor Name": "டாக்டர் பெயர்",
  "Health Status": "சுகாதார நிலை",
  "Checkup Time": "சோதனை நேரம்",
  "CANCELED": "ரத்து செய்யப்பட்டது",
  "NORMAL": "இயல்பு",
  "Case Summary": "வழக்கு சுருக்கம்",
  "Prescription": "மருந்து",
  "Tablets": "மாத்திரைகள்",
  "Units": "அலகுகள்",
  "Timing": "நேரம்",
  "Requested lab supported": "கோரிய ஆய்வகம் ஆதரிக்கப்படுகிறது",
  "Next Appointment Date": "அடுத்த சந்திப்பு தேதி",
  "Next Appointment Time": "அடுத்த சந்திப்பு நேரம்",
  "Symptoms": "அறிகுறிகள்",
  "Are you sure to cancel the appointment?":
      "நிச்சயமாக அப்பாயின்ட்மென்ட்டை ரத்து செய்யலாமா?",
  "Screening": "திரையிடல்",
  "Go to Screening": "ஸ்கிரீனிங்கிற்கு செல்",
  "Reports": "அறிக்கைகள்",
  "Report Details": "அறிக்கை விவரங்கள்",
  "Report": "அறிக்கை",
  "SCAN AND ADD NEW REPORT": "ஸ்கேன் செய்து புதிய அறிக்கையைச் சேர்",
  "Click Add Images Button": "படங்களைச் சேர் பொத்தானைக் கிளிக் செய்க",
  "NO IMAGE": "உருவம் இல்லை",
  "No Report Added": "அறிக்கை சேர்க்கப்படவில்லை",
  "ADD IMAGE": "படத்தைச் சேர்",
  "Choose Photo from :": "இதில் இருந்து புகைப்படத்தைத் தேர்ந்தெடுங்கள் :",
  "Type of Report": "அறிக்கை வகை",
  "Write Description": "விளக்கத்தை எழுது",
  "ADD REPORT": "அறிக்கையைச் சேர்",
  "Report Added Successfully": "அறிக்கை வெற்றிகரமாக சேர்க்கப்பட்டது",
  "Report Deleted Successfully": "அறிக்கை வெற்றிகரமாக நீக்கப்பட்டது",
  "Report Date: ": "அறிக்கை தேதி: ",
  "After Food": "உணவுக்குப் பிறகு",
  "Before Food": "உணவுக்கு முன்",
  "Before Walk": "நடைபயிற்சி முன்",
  "After Walk": "நடைபயிற்சி பிறகு",
  "Report Time: ": "அறிக்கை நேரம்: ",
  "Report desc: ": "அறிக்கை விவரம்: ",
  "UPDATE IMAGE": "படத்தைப் புதுப்பி",
  "DELETE REPORT": "அறிக்கையை நீக்கு",
  "UPDATE REPORT": "புதுப்பிப்பு அறிக்கை",
  "Report Updated Successfully": "அறிக்கை வெற்றிகரமாக புதுப்பிக்கப்பட்டது",
  "Education": "கல்வி",
  "Knowledge Transfer": "அறிவு பரிமாற்றம்",
  "Sorry No Awareness Post Found":
      "மன்னிக்கவும் விழிப்புணர்வு இடுகை எதுவும் கிடைக்கவில்லை",
  "Patient List": "நோயாளிகள் பட்டியல்",
  "Search Patient By Name": "பெயரால் நோயாளியைத் தேடுங்கள்",

//Chat screen

  "Chat": "அரட்டை",
  "PATIENTS": "நோயாளிகள்",
  "DOCTORS": "டாக்டர்கள்",
  "NURSE": "செவிலியர்",
  "Type a message": "செய்தியை உள்ளிடவும்",
  "View Case Details": "வழக்கு விவரங்களைக் காண்க",

//Settings Screen

  "Settings": "அமைப்புகள்",
  "General Details": "பொது விவரங்கள்",
  "Year of Experience": "அனுபவ ஆண்டு",
  "Title": "தலைப்பு",
  "Address": "முகவரி",
  "Edit Profile": "சுயவிவரத்தைத் திருத்து",
  "Notification": "அறிவிப்பு",
  "ON": "ஆன்",
  "OFF": "ஆஃப்",
  "Terms & Conditions": "விதிமுறைகளும் நிபந்தனைகளும்",
  "Privacy Policy": "தனியுரிமைக் கொள்கை",
  "Help": "உதவி",
  "Contact Us": "எங்களை தொடர்பு கொள்ள",
  "Tell us what's going on": "என்ன நடக்கிறது என்று சொல்லுங்கள்",
  "Tell us why you're reaching us":
      "நீங்கள் ஏன் எங்களை அணுகுகிறீர்கள் என்று சொல்லுங்கள்",
  "Something not Working": "ஏதோ வேலை செய்யவில்லை",
  "Feature Request": "சிறப்பு விண்ணப்பம்",
  "Question": "கேள்வி",
  "FeedBack": "பின்னூட்டம்",
  "How do you feel? (Optional)": "நீங்கள் எப்படி உணர்கிறீர்கள்? (விரும்பினால்)",
  "SEND": "அனுப்பு",
  "App Info": "பயன்பாட்டுத் தகவல்",
  "Log out": "வெளியேறு",
  "Are you sure to log out?": "நீங்கள் நிச்சயமாக வெளியேறுகிறீர்களா?",
  "No": "இல்லை",
  "Yes": "ஆம்",
  "Other": "மற்றவை",
  "Language": "மொழி",
};
