// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTIZnQCNHOYfhO2knrgr8HlJMzldTKzY',
    appId: '1:492221570730:web:13b6010303750937ea7ad3',
    messagingSenderId: '492221570730',
    projectId: 'savemom-healthcare',
    authDomain: 'savemom-healthcare.firebaseapp.com',
    databaseURL: 'https://savemom-healthcare-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'savemom-healthcare.appspot.com',
    measurementId: 'G-KCL4PTS6X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyVPpgSEVJpi77S8Q5aN9VLSsaJjz0UKI',
    appId: '1:492221570730:android:06b51f6abf15e62cea7ad3',
    messagingSenderId: '492221570730',
    projectId: 'savemom-healthcare',
    databaseURL: 'https://savemom-healthcare-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'savemom-healthcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjOuTSEt1EXZPnmIPRqxwkKX4XzpWANQ',
    appId: '1:492221570730:ios:8dd6d2ac7d3806c7ea7ad3',
    messagingSenderId: '492221570730',
    projectId: 'savemom-healthcare',
    databaseURL: 'https://savemom-healthcare-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'savemom-healthcare.appspot.com',
    androidClientId: '492221570730-0bgdn40820ooplpsn14undq682ejhcu0.apps.googleusercontent.com',
    iosClientId: '492221570730-uteudtg7r1s4gjbvm45ui7jjgp2as4qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.allolab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa-NxVKqQk1biMwQTD5OAu7cwRGaHl9EE',
    appId: '1:492221570730:web:2327bc2d92f39cafea7ad3',
    messagingSenderId: '492221570730',
    projectId: 'savemom-healthcare',
    authDomain: 'savemom-healthcare.firebaseapp.com',
    databaseURL: 'https://savemom-healthcare-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'savemom-healthcare.appspot.com',
    measurementId: 'G-5YWEHM3NWZ',
  );
}
